"""Pydantic schemas for the public API.

The request shape accepts both free-text user goals (the original CLI
profile) and an optional pre-classified equipment list. The response
mirrors the JSON schema enforced by stage 3 of the prompt.
"""
from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class UserProfile(BaseModel):
    """One-shot profile passed with each request. No persistent storage —
    the caller (Laravel) is responsible for stitching this together from
    the user's account and the form they filled in."""

    body_weight: Optional[str] = Field(None, description="e.g. '70 kg' or just '70'")
    height: Optional[str] = Field(None, description="e.g. '170 cm' or just '170'")
    age: Optional[str] = Field(None, description="e.g. '30' or '30 years'")
    sex: Optional[str] = Field(None, description="male / female / other")
    fitness_goals: Optional[str] = Field(None, description="fat loss, muscle gain, …")
    exercise_preference: Optional[str] = Field(None, description="strength / cardio / mixed")
    time_available: Optional[str] = Field(None, description="e.g. '45 minutes'")
    available_days: Optional[str] = Field(None, description="e.g. 'Mon, Wed, Fri' or '4 days/week'")
    equipment_available: Optional[str] = Field(
        None, description="Free-text equipment description; auto-mapped to canonical labels.",
    )
    body_part_focus: Optional[str] = Field(None, description="e.g. 'full body', 'legs', 'chest'")
    limitations: Optional[str] = Field(
        None, description="Injuries or conditions to work around — fed into the assessment stage.",
    )


class GenerateRequest(BaseModel):
    profile: UserProfile
    query: Optional[str] = Field(
        default="Create a weekly exercise routine",
        description="Free-text user request; defaults to a fresh weekly routine.",
    )


# --- Response schema, mirrors the JSON the LLM is instructed to emit ---


class WorkoutExercise(BaseModel):
    exercise_id: Optional[str] = None
    name: str
    detail: Optional[str] = None        # e.g. "4 sets × 8-10 reps, 90s rest"
    description: Optional[str] = None   # instructions or technique notes
    duration: Optional[str] = None      # e.g. "12 minutes"
    body_part: Optional[str] = None
    equipment: Optional[str] = None
    target: Optional[str] = None


class WorkoutDay(BaseModel):
    day_label: str
    heading: Optional[str] = None
    title: Optional[str] = None
    duration: Optional[str] = None
    description: Optional[str] = None
    exercises: list[WorkoutExercise] = Field(default_factory=list)


class WeeklyPlan(BaseModel):
    """The full response body."""
    assessment: Optional[str] = Field(
        default=None,
        description="Stage-1 health assessment. Useful for the UI's 'safety notes' section.",
    )
    weekly_structure: Optional[str] = Field(
        default=None,
        description="Stage-2 weekly outline before exercise selection.",
    )
    weekly_workout_plan: list[WorkoutDay] = Field(default_factory=list)
    equipment_resolved: list[str] = Field(
        default_factory=list,
        description="Canonical equipment labels derived from `equipment_available`.",
    )
    disclaimer: str = (
        "This plan is generated by an AI assistant and is for general fitness "
        "guidance only. Consult a qualified professional before starting a new "
        "exercise program, especially if you have any medical conditions or injuries."
    )
