from typing import Literal

from pydantic import BaseModel, Field


class ExerciseRequest(BaseModel):
    goal: Literal["lose_weight", "build_muscle", "improve_endurance", "general_fitness"] = "general_fitness"
    level: Literal["beginner", "intermediate", "advanced"] = "beginner"
    days_per_week: int = Field(3, ge=1, le=7)
    minutes_per_session: int = Field(30, ge=10, le=180)
    equipment: list[str] = Field(default_factory=list, description="e.g. ['dumbbells', 'mat']")
    limitations: list[str] = Field(
        default_factory=list,
        description="Injuries / conditions to work around, e.g. ['knee pain'].",
    )


class ExerciseSet(BaseModel):
    name: str
    sets: int | None = None
    reps: str | None = None  # "10" or "30s" or "AMRAP"
    rest_seconds: int | None = None
    notes: str | None = None


class ExerciseDay(BaseModel):
    day: str  # e.g. "Monday" or "Day 1"
    focus: str  # e.g. "Upper body" / "Cardio + core"
    warmup: list[str] = Field(default_factory=list)
    workout: list[ExerciseSet] = Field(default_factory=list)
    cooldown: list[str] = Field(default_factory=list)


class ExercisePlan(BaseModel):
    summary: str
    weekly_plan: list[ExerciseDay]
    safety_notes: list[str] = Field(default_factory=list)
    disclaimer: str = (
        "This plan is generated by an AI assistant and is for general fitness guidance only. "
        "Consult a qualified professional before starting a new exercise program, especially if "
        "you have any medical conditions or injuries."
    )
